# Generated by Django 3.0.8 on 2020-07-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_showtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم'},
        ),
    ]
